name = "PackageExtensionsExample"
uuid = "1150551f-27a8-42dc-b999-d7a8701b0574"
authors = ["itsdfish"]
version = "1.0.0-DEV"

[deps]

[weakdeps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[extensions]
DistributionsExt = "Distributions"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
